<?php
// $Id: bettermenus.module,v 1.1 2010/06/01 08:32:39 blixxxa Exp $

/**
 * @file
 * Better menus module.
 */

/**
 * Implementation of hook_menu().
 */
function bettermenus_menu() {
  $items = array();
  
  $items['admin/settings/bettermenu'] = array(
    'title' => 'Better menus',
    'description' => 'Settings for Better menus module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bettermenus_settings'),
    'access arguments' => array('administer site configuration'),
  );
  
  return $items;
}

/**
 * Callback; Settings page.
 */
function bettermenus_settings() {
  $form = array();
  
  $menus = menu_get_menus();
  $default = menu_get_names();
  
  $form['bettermenus_available_menus'] = array(
    '#title' => t('Available menus'),
    '#description' => t('Select the menus you want available in the menu selection widget.'),
    '#type' => 'select',
    '#default_value' => variable_get('bettermenus_available_menus', $default),
    '#options' => $menus,
    '#multiple' => TRUE,
  );
  
  return system_settings_form($form);
}

/**
 * Implementation of hook_form_alter().
 */
function bettermenus_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'page_node_form') {
    $path = drupal_get_path('module', 'bettermenus');
    drupal_add_js($path.'/jsTree/jquery.tree.js');
    drupal_add_js($path.'/js/bettermenus.min.js');
    drupal_add_css($path.'/bettermenus.css');
    drupal_add_css($path.'/jsTree/themes/classic/classic.css');
    
    // Tree control.
    $form['menu_tree'] = array(
      '#type' => 'fieldset',
      '#title' => t('Menu'),
      '#weight' => $form['menu']['#weight'] - 1,
      '#tree' => TRUE,
    );
    
    // Tree placeholder.
    $form['menu_tree']['tree'] = array(
      '#prefix' => '<div id="menu-tree-wrapper" class="form-item clear-block">',
      '#suffix' => '</div>',
      '#value' => bettermenus_tree('primary-links', $form['menu']['mlid']['#value']),
    );
    
    // Add button.
    $form['menu_tree']['add_new'] = array(
      '#type' => 'button',
      '#button_type' => 'button',
      '#value' => t('Add new'),
    );
    
    // Rename button.
    $form['menu_tree']['rename'] = array(
      '#type' => 'button',
      '#button_type' => 'button',
      '#value' => t('Rename'),
      '#disabled' => TRUE,
    );
    
    // Delete button.
    $form['menu_tree']['delete'] = array(
      '#type' => 'button',
      '#button_type' => 'button',
      '#value' => t('Delete'),
      '#disabled' => TRUE,
    );
    
    drupal_add_js(array('bettermenus' => array('path' => drupal_get_path('module', 'bettermenus'))), 'setting');
  }
}

/**
 * Build HTML menu.
 */
function bettermenus_tree($menu = 'primary-links', $current_mlid = NULL) {
  // Get avialable menus.
  $default = menu_get_names();
  $available_menus = variable_get('bettermenus_available_menus', $default);
  $menus = menu_get_menus();
  
  // Build tree output.
  $tree = '<ul>';
  foreach ($menus as $menu => $name) {
    if (!in_array($menu, $available_menus)) {
      continue;
    }
    $options = menu_tree_all_data($menu, NULL);
    $tree .= sprintf('<li id="%s_0" rel="%s"><a href="#"><ins>&nbsp;</ins>%s</a>', $menu, 'root', $name);
    $tree .= bettermenus_build_tree($options, $current_mlid);
    $tree .= '</li>';
  }
  $tree .= '</ul>';
  return $tree;
}

/**
 * Build HTML UL list from array.
 */
function bettermenus_build_tree($options, $current_mlid = NULL) {  
  if (!empty($options)) {
    $tree = '<ul>';
    foreach ($options as $option) {
      if ($option['link']['hidden'] >= 0) {
        // What type of link is this?
        if ($option['link']['mlid'] == $current_mlid) {
          $type = 'current';
          drupal_add_js(array('bettermenus' => array('selected' => "{$option['link']['menu_name']}_{$option['link']['mlid']}_{$option['link']['weight']}")), 'setting');
        }
        else if ($option['link']['hidden']) {
          $type = 'hidden';
        }
        else {
          $type = 'default';
        }
        $tree .= sprintf('<li id="%s_%s_%s" rel="%s"><a href="#"><ins>&nbsp;</ins>%s</a>', $option['link']['menu_name'], $option['link']['mlid'], $option['link']['weight'], $type, $option['link']['title']);
        if ($option['link']['has_children']) {
          $tree .= bettermenus_build_tree($option['below'], $current_mlid);
        }
        $tree .= '</li>';
      }
    }
    $tree .= '</ul>';
  }
  return $tree;
}
