<?php
// $Id: nodewords_extra.module,v 1.1.2.58 2010/02/14 11:22:23 kiam Exp $

/**
 * @file
 * Define extra meta tags for Drupal pages.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nodewords_extra_form_nodewords_settings_form_alter(&$form, &$form_state) {
  $form['metatags_creation']['nodewords_add_dc_schema'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add the Dublin Core schema meta tag'),
    '#default_value' => variable_get('nodewords_add_dc_schema', FALSE),
  );
}

/**
 * Implements hook_menu().
 */
function nodewords_extra_menu() {
  $items = array();

  $items['labels.rdf'] = array(
    'title' => 'ICRA labels',
    'page callback' => 'nodewords_extra_verification_content',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_nodewords_api().
 */
function nodewords_extra_nodewords_api() {
  return array(
    'api' => '1.12',
    'path' => '',
  );
}

/**
 * Implements hook_perm().
 */
function nodewords_extra_perm() {
  return array(
    'edit meta tag Dublin Core CONTRIBUTOR',
    'edit meta tag Dublin Core CREATOR',
    'edit meta tag Dublin Core DATE',
    'edit meta tag Dublin Core DESCRIPTION',
    'edit meta tag Dublin Core PUBLISHER',
    'edit meta tag Dublin Core TITLE',
    'edit location meta tag',
    'edit meta tag PICS-LABEL',
    'edit short URL meta tag',
  );
}

function nodewords_extra_verification_content() {
  drupal_set_header('Content-Type: application/rdf+xml; charset=utf-8');

  print variable_get('nodewords_icra_validation_content', '');
}
